### PR TITLE
add `parinfer-rust-disable-troublesome-modes` to disable prompting and disable mode directly

### PR DESCRIPTION
**Pull request by Flinner**
Disables troublesome modes without prompting the user.

This 'defaults' the prompt to always `yes` (actually ignores the prompt) and disable the troublesome mode directly

should it be named `parinfer-rust-auto-disable-troublesome-modes`?

### CODE REVIEW

**Comment by Flinner** [comment]
I am unable to find why the CI fails. It fails while running it locally even without my commit.

maybe it needs updating? :c

**Comment by justinbarclay** [comment]
Hey @Flinner, 
Thanks for the PR. I'm bogged down with work and life at the moment. But I promise I'll try to find time in the next month to look at this. (Sorry, it can't be sooner)

**Comment by Flinner** [comment]
Hi, I hope you are doing well my friend.

I am not in hurry at all, please take your time. I am just wondering if this feature will be added in the future or do I just make a fork for myself :sweat_smile:.

**Review by justinbarclay — APPROVED** [review]
Hey, thanks for poking me on this. It caused me to finally go through this repo and make some other updates as well. Like move testing to github so it's easier for others to run it.

Anyways 👍

**Comment by justinbarclay** [comment]
I tried merging your work onto main, hoping that would automatically pick up the right tests. But it doesn't look like it, I'll merge this regardless. 

Once again, thank you for your work and sorry for the massive delay 😳

**Comment by Flinner** [comment]
Thanks!!
should we expect a new release anytime soon?

**Comment by justinbarclay** [comment]
Yeah, on [melpa](https://melpa.org/#/parinfer-rust-mode) it's a rolling release. (Get's picked up within ~2-3 hours).
And I've added a tag now, too so that it's on [melpa stable](https://stable.melpa.org/#/parinfer-rust-mode)

**Pull request merged**
