### PR TITLE
Refactoring

### LINKED ISSUE #14: Code style refactoring
First of all, I think that no files should make Parinfer angry. Here are two existing problems:

- `parinfer-rust-changes.el`, `test-helper.el` require some indentation fixing (reported by parinfer);
- Many files have unbalanced quotes in comments.
  I guess we should use `electric-quote-mode` (inbuilt) that replaces `'` with `’` to completely avoid this problem, perhaps enable it with modeline `-*- electric-quote-mode: t -*-`?

Another thing I've noticed that there are variables named with `-p` which is a notation for predicate functions. I've never seen boolean variables named like that. There's [excellent style guide](https://github.com/bbatsov/emacs-lisp-style-guide#naming) by Bozhidar Batsov, that I guess we can use to make code more concise.

I'm going to submit PR with these fixes for you to review.

### PR DESCRIPTION
**Pull request by andreyorst**
fix #14

(This PR is going to be big, so feel free to make a lot of comments and request changes)

### CODE REVIEW

**Comment by andreyorst** [comment]
I'm not sure, maybe it's needed, but why `(not (not (...)))`? 

https://github.com/justinbarclay/parinfer-rust-mode/blob/95bf9baa6f000eb577f81ebc74d2236d8e06442b/parinfer-rust-mode.el#L79

I think double negation should cancel itself, no?

**Comment by andreyorst** [comment]
During edits I've spotted some warnings from flymake, you should take a look at `goto-line`, maybe you should replace it with `forward-line`.

**Comment by justinbarclay** [comment]
I would be cautious of doing too much work on this for now, my work on [melpa](https://github.com/justinbarclay/parinfer-rust-mode/tree/melpa) is far reaching and touches a lot of the files

**Comment by andreyorst** [comment]
It's not a big deal - most of edits I did were either automated, or a global replace, so even if many files will be changed I will be able to rebase and fix everything :)

Or maybe you can cherry pick from this and close without merging.

**Comment by andreyorst** [comment]
Another thing that bothers me a bit is amount of `-p` variables. Usually `-p` is only used for predicate functions, and boolean variables are named with imperative words in those, implying some action that will be taken, if variable is non-nil. Not that it affects the code, in any way, but I'm looking at it and want to rename everything. What's your opinion?

**Comment by justinbarclay** [comment]
1. `goto-line` was only used in testing infrastructure and in the melpa branch has been cleaned up
2. `(not (not` I think is sort of vestigial code/ dead at this point and needs to be refactored. At the time when I wrote that I was looking at converting an env var representing a boolean to a boolean in lisp. Unfortunately, earlier this week I found that wasn't working as I had intended and now I need to add it to my list of things to refactor.
3. I understand the common use of `-p` and I appreciate the want for consistency. But honestly, I have grown attached to just thinking of the idea of `-p` meaning that a _predicate value_ exists here, either in the function or variable name space. It's now become a short hand for me when reading through this and decided whether an action, or some set of actions, should be done. If you want to rename them, I'm open for suggestions for the future. But, at the moment, I'm too comfortable in my conventions to change just yet.

**Comment by justinbarclay** [comment]
Looks like you "win" with `-p` 😉. 
I'm reading though [MELPA contribution guide](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#making-your-package-ready-for-inclusion), and they mention following Bozhidar's style guide.

**Comment by andreyorst** [comment]
should I rebase and help with applying style changes?

**Comment by justinbarclay** [comment]
I would appreciate that.

I've ported your commit "do not quote t Boolean" and really liked the work you've done with the docstrings (that is next up on my list).

I'm not a big fan of curved quotes, but I am curious to hear why that is something you prefer.

**Comment by andreyorst** [comment]
> I'm not a big fan of hesitant to switch to curved quotes, but I am curious to hear why that is something you prefer.

As I've mentioned in #14 

>- Many files have unbalanced quotes in comments.
>  I guess we should use electric-quote-mode (inbuilt) that replaces ' with ’ to completely avoid this problem, perhaps enable it with modeline -*- electric-quote-mode: t -*-?

I think this is nice solution for Emacs package, since we only edit the code in Emacs, so everyone will have `electric-quote-mode` and there will be no problems with quotes in comments, that Parinfer has issues with.

> I would appreciate that.

What branch should I rebase from? I see you've pushed to master, but there's melpa branch too which is slightly behind

**Comment by justinbarclay** [comment]
Off of master please :)

**Comment by andreyorst** [comment]
OK I'll do this in couple of hours :)

**Comment by andreyorst** [comment]
I've rebased on your current master, and altered docstrings a bit. I did not touch code, but I've noticed these two bits:

    (locate-user-emacs-file (concat "parinfer-rust/" parinfer-rust--lib-name))

Maybe just use `(concat user-emacs-directory "parinfer-rust/" parinfer-rust--lib-name)`? Although I'm unfamiliar with locating emacs directory, so maybe your code is more correct.

Another thing is that you seem to use `(list ...)` in many places where `'(...)` will do, like lists of strings. And about the strings - maybe it is better to replace mode strings with symbols? E.g. `'smart`, `'indent`, and `'paren`. Comparing symbols should be less expensive than string comparison.

**Comment by andreyorst** [comment]
Nothing catches my eye, so I guess PR is ready for review/merge

**Comment by justinbarclay** [comment]
This looks really good thank you.

As for your questions (which I really enjoyed):
> ```
> (locate-user-emacs-file (concat "parinfer-rust/" parinfer-rust--lib-name))
> ```
> 
> Maybe just use `(concat user-emacs-directory "parinfer-rust/" parinfer-rust--lib-name)`? Although I'm unfamiliar with locating emacs directory, so maybe your code is more correct.

My intent when I wrote this was to have emacs create the directory for me if necessary.
> Return an absolute per-user Emacs-specific file name.
> If NEW-NAME exists in ‘user-emacs-directory’, return it.
> Else if OLD-NAME is non-nil and ~/OLD-NAME exists, return ~/OLD-NAME.
> Else return NEW-NAME in ‘user-emacs-directory’, **creating the**
> **directory if it does not exist.**

(bold added for emphasis)

> Another thing is that you seem to use (list ...) in many places where '(...), will do, like lists of strings.

In this PR I see some places where you removed some superfluous lists in changes, where I was using them as type hints while I was exploring solutions. 

You also transitioned the list of strings to list ala:
```elisp
(defconst parinfer-rust--mode-types '("indent" "smart" "paren")
  "The different modes that parinfer can operate on.")
```
Thank you for cleaning these up. :)

But grepping through the rest of the core package, I am not sure I see other lists of strings or data that could used as `'(...)` instead of `(list ...)`
The other calls to list that I see are similar to:

```elisp
(list
     'lineNo (plist-get change-a 'lineNo)
     'x (plist-get change-a 'x)
     'start start
     'end end
     'length length
     'before-text (string-join (list (plist-get change-a 'before-text)
                                     (plist-get change-b 'before-text)))
     'after-text (string-join (list (plist-get change-a 'after-text)
                                    (plist-get change-b 'after-text)))
     'group t)
```
These calls to list have function calls in them and therefore can't be treated as literal data. Are there others I might be missing? If so what are your ideas there?

> E.g. 'smart, 'indent, and 'paren. Comparing symbols should be less expensive than string comparison.

I would have thought that comparing symbols would have been quicker/less expensive as well. Doing some quick benchmarking on my machine leads me to believe otherwise:

```elisp
(benchmark-run 1000000
  (string= "smart" "indent"))
;=> (0.023956999999999992 0 0.0)
```

```elisp
(benchmark-run 1000000
  (equal 'smart 'indent))
;=> (0.0420267 0 0.0)
```

It looks like for _small_ strings it's actually faster to check for equality then checking for equality of symbols. 
Note: for equality checking on symbol, I used `equal` over `eq` because it appeared to be faster.

The other piece of info we need to look as is converting the symbol to a string (to pass to parinfer-rust library)
```elisp
(benchmark-run 1000000
  (symbol-name 'indent))
;=> (0.026604000000000003 0 0.0)
```

I hope these answers are sufficient, but I'm willing to dig deeper into any of them :)

**Comment by andreyorst** [comment]
Whoa, thanks for the answer.

> My intent when I wrote this was to have emacs create the directory for me if necessary.

Ah, that's the bit I was missing.

> These calls to list have function calls in them and therefore can't be treated as literal data. Are there others I might be missing? If so what are your ideas there?

No no no, I was only mentioning such places where lists could be replaced with literals. The list call you've listed is fine. It *can( be replaced with...

```emacs-lisp
`(lineNo ,(plist-get change-a 'lineNo)
  x ,(plist-get change-a 'x)
  start ,start
  end ,end
  length ,length
  before-text ,(string-join (list (plist-get change-a 'before-text)
                                 (plist-get change-b 'before-text)))
  after-text ,(string-join (list (plist-get change-a 'after-text)
                                (plist-get change-b 'after-text)))
  group t)
```

...but it makes little sense to do so when every item has to be evaluated

>It looks like for small strings it's actually faster to check for equality then checking for equality of symbols.
>Note: for equality checking on symbol, I used equal over eq because it appeared to be faster.

This is unexpected.

---

>This looks really good thank you.

No, it's thank you for bringing parinfer rust to Emacs :)

**Pull request merged**
